# Generated by Django 5.1.5 on 2025-01-15 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(help_text='Age in weeks')),
                ('breed', models.CharField(max_length=50)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Deceased', 'Deceased')], default='Healthy', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_collected', models.DateField()),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eggs', to='inventory.chicken')),
            ],
        ),
    ]
