# Generated by Django 5.1.5 on 2025-01-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='health_status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Deceased', 'Deceased')], max_length=10),
        ),
        migrations.AlterField(
            model_name='egg',
            name='chicken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.chicken'),
        ),
    ]
